### ISSUE TITLE
401 unauthorised

### ISSUE THREAD

**Issue by robertandrews** [anhi/obsidian-notion-connector#1]
When run, the dialog remains open.
Developer Tools console shows a 401 error re failed authorisation.

I have entered the appropriate API key.
I have shared the specific test page with the API integration.

**Comment by anhi** [comment]
Could you try adding the line

console.log(url)

to line 1837 of main.js (should be located in .obsidian/plugins/obsidian-notion-connector) and try to run the download again?

In the developer tools, you should see the URL object. If you expand that, can you check that it uses the correct API token in the authorization header?

**Comment by robertandrews** [comment]
I've tested successfully making a connection for a particular page via Integromat...

* Page is shared with the API integration.
* Endpoint https://api.notion.com/v1/pages/mypageid is used.
* Call returns an object with code 200.

With this plugin, however...

```
Error: Request failed, status 401
    at new t (app.js:1:699465)
    at nw (app.js:1:699657)
    at app.js:1:700334
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
```
and...

`Could not sync with notion! plugin:obsidian-notion-connector:2104`

and...

```
downloadFromNotionToFile	@	plugin:obsidian-notion-connector:2104
await in downloadFromNotionToFile (async)		
downloadFromNotion	@	plugin:obsidian-notion-connector:2147
eval	@	plugin:obsidian-notion-connector:2199
eval	@	plugin:obsidian-notion-connector:2169
(anonymous)	@	app.js:1
```

In your API call, the actual secret API key, which I saved in settings and which was still showing when I went back into settings, does not _actually_ get added after "Bearer " ...

Unless I restart Obsidian. 

When I _then_ ran the process, it chugged through pulling all the child blocks.

**Comment by anhi** [comment]
Good catch. The notion client was not correctly reinitialized upon token changes. I've pushed a new version that should fix this.
